In [1]:
import pandas
import pandas as pd

In [2]:
oo = pd.read_csv('C:\\Users\\USER\Desktop\\LINKEDIN_LEARNING\\Ex_Files_Pandas_EssT\\Ex_Files_Pandas_EssT\\ExerciseFiles\\data\\olympics.csv', skiprows=4)

In [3]:
oo

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
...,...,...,...,...,...,...,...,...,...,...
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

# Which three countries have won the most medals in recent years (from 1984 to 2008)

In [5]:
rec=oo[oo.Edition >=1984]
rec

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
16592,Los Angeles,1984,Aquatics,Diving,"LI, Kong-Zheng",CHN,Men,10m platform,M,Bronze
16593,Los Angeles,1984,Aquatics,Diving,"LOUGANIS, Gregory",USA,Men,10m platform,M,Gold
16594,Los Angeles,1984,Aquatics,Diving,"KIMBALL, Bruce D.",USA,Men,10m platform,M,Silver
16595,Los Angeles,1984,Aquatics,Diving,"WYLAND-WILLIAMS, Wendy Lian",USA,Women,10m platform,W,Bronze
16596,Los Angeles,1984,Aquatics,Diving,"ZHOU, Ji-Hong",CHN,Women,10m platform,W,Gold
...,...,...,...,...,...,...,...,...,...,...
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [7]:
rec.NOC.value_counts().head(3)

USA    1837
AUS     762
GER     691
Name: NOC, dtype: int64